config/routes.rb
Rails.application.routes.draw do
  get '/auth/stripe/connect', to: 'stripe#connect', as: 'stripe_connect'
  get '/auth/stripe/create_account', to: 'stripe#create_account', as: 'stripe_create_account'
  get '/auth/stripe/callback', to: 'stripe#callback', as: 'stripe_callback'
  get "stripe/dashboard/:user_id", to: "stripe#dashboard", as: :stripe_dashboard

  devise_for :users
  resources :checkout, only: [:show]

  resources :invoices, only: [:show] do
    member do
      get 'success', to: 'invoices#success'
    end
  end
  
  resources :orders
  resources :bids
  resources :requests do
    member do
      patch :accept_bid
    end
  end
  post 'generate_invoice', to: 'invoices#generate', as: 'generate_invoice'


  resources :buyers
  resources :vendors
  resources :profiles, only: [:show, :edit, :update]
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  get 'dashboard', to: 'dashboard#index'

 root to: 'home#index'
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
end

app/controllers/profiles_controller.rb
# app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[edit update]
  layout 'dashboard'

  def edit
    @profile = current_user.profile
  end

  def update
    if @profile.update(profile_params)
      flash[:notice] = 'Profile was successfully updated.'
      redirect_to edit_profile_path
    else
      render :edit
    end
  end

  private

  def set_profile
    @profile = current_user.profile
  end

  def profile_params
    params.require(:profile).permit(:business_name, :about, :street_address, :avatar, :city, :state, :zip_code, :phone, :email_address, :first_name, :last_name)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<div class="mx-auto max-w-7xl py-5 px-4 sm:px-6 lg:px-8">

<div class="mx-auto bg-white rounded-md max-w-7xl py-5 px-4 sm:px-6 lg:px-8">
<%= form_with(model: @profile, local: true) do |form| %>
<div class="space-y-12">
  <div class="border-b border-gray-900/10 pb-12">
    <h2 class="text-base font-semibold leading-7 text-gray-900">Business Profile</h2>
    <p class="mt-1 text-sm leading-6 text-gray-600">Enter the details about your business here.</p>

    <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
      <div class="sm:col-span-4">
        <%= form.label :business_name, class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.text_field :business_name, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <div class="col-span-full">
        <%= form.label :about, class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.text_area :about, rows: 3, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
        <p class="mt-3 text-sm leading-6 text-gray-600">Tell us a little about your business.</p>
      </div>
    </div>
  </div>

   <div class="col-span-full">
          <label for="photo" class="block text-sm font-medium leading-6 text-gray-900">Photo</label>
         
          <div class="mt-2 flex items-center gap-x-3">
             <% if @profile.avatar.attached? %>
              <%= image_tag @profile.avatar.variant(resize_to_limit: [100, 100]), class: 'rounded-full h-12 w-12' %>
            <% end %>
           
            <%= form.file_field :avatar, class:'rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50'%>
          </div>
        </div>

  <div class="border-b border-gray-900/10 pb-12">
    <h2 class="text-base font-semibold leading-7 text-gray-900">Business Location </h2>
    <p class="mt-1 text-sm leading-6 text-gray-600">This is to connect you with businesses in your region.</p>

    <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
      <div class="sm:col-span-3">
        <%= form.label :first_name, "First name", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.text_field :first_name, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <div class="sm:col-span-3">
        <%= form.label :last_name, "Last name", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.text_field :last_name, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <div class="sm:col-span-4">
        <%= form.label :email_address, "Email address", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.email_field :email_address, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

    
      <div class="col-span-full">
        <%= form.label :street_address, "Street address", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.text_field :street_address, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <div class="sm:col-span-2 sm:col-start-1">
        <%= form.label :city, "City", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.text_field :city, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <div class="sm:col-span-2">
        <%= form.label :state, "State / Province", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.text_field :state, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <div class="sm:col-span-2">
        <%= form.label :zip_code, "ZIP / Postal code", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.text_field :zip_code, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>
    </div>
  </div>

   <div class="sm:col-span-2">
   
      <p class="mt-5 text-sm leading-6 text-gray-600">We use Stripe to process payments and handle payouts to our musicians. <br /> Connect your Stripe account to start getting paid.</p><br />


<% if current_user.stripe_status == "incomplete" %>
  <%= link_to 'Connect with Stripe', stripe_create_account_path, class: "rounded-md bg-indigo-600 mt-10 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
<% else %>
        <%= link_to "Go to Stripe Dashboard", stripe_dashboard_path(current_user.id), class:"rounded-md bg-indigo-600 mt-10 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
<% end %>      
    



    </div>


</div>

<div class="mt-6 flex items-center justify-end gap-x-6">
  <%= link_to 'Cancel', dashboard_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
  <%= form.submit 'Save', class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
</div>
<% end %>
</div>
</div>

app/views/profiles/show.html.erb
<div class="mx-auto max-w-7xl py-5 px-4 sm:px-6 lg:px-8">


<div class="overflow-hidden rounded-lg bg-white shadow">
  <h2 class="sr-only" id="profile-overview-title">Profile Overview</h2>
  <div class="bg-white p-6">
    <div class="sm:flex sm:items-center sm:justify-between">
      <div class="sm:flex sm:space-x-5">
        <div class="flex-shrink-0">
          <img class="mx-auto h-20 w-20 rounded-full" src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
        </div>
        <div class="mt-4 text-center sm:mt-0 sm:pt-1 sm:text-left">
          <p class="text-sm font-medium text-gray-600">Welcome back,</p>
          <p class="text-xl font-bold text-gray-900 sm:text-2xl">Rebecca Nicholas</p>
          <p class="text-sm font-medium text-gray-600">Product Designer</p>
        </div>
      </div>
      <div class="mt-5 flex justify-center sm:mt-0">
        <a href="#" class="flex items-center justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">View profile</a>
      </div>
    </div>
  </div>
  












</div>