config/routes.rb
Rails.application.routes.draw do
  get '/auth/stripe/connect', to: 'stripe#connect', as: 'stripe_connect'
  get '/auth/stripe/create_account', to: 'stripe#create_account', as: 'stripe_create_account'
  get '/auth/stripe/callback', to: 'stripe#callback', as: 'stripe_callback'
  get "stripe/dashboard/:user_id", to: "stripe#dashboard", as: :stripe_dashboard

  devise_for :users
  resources :checkout, only: [:show]

  resources :invoices, only: [:show] do
    member do
      get 'success', to: 'invoices#success'
    end
  end
  
  resources :orders
  resources :bids
  resources :requests do
    member do
      patch :accept_bid
    end
  end
  post 'generate_invoice', to: 'invoices#generate', as: 'generate_invoice'


  resources :buyers
  resources :vendors
  resources :profiles, only: [:show, :edit, :update]
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  get 'dashboard', to: 'dashboard#index'

 root to: 'home#index'
end

app/models/buyer.rb
class Buyer < ApplicationRecord
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :set_buyer, only: %i[ show edit update destroy ]

  # GET /buyers or /buyers.json
  def index
    @buyers = Buyer.all
  end

  # GET /buyers/1 or /buyers/1.json
  def show
  end

  # GET /buyers/new
  def new
    @buyer = Buyer.new
  end

  # GET /buyers/1/edit
  def edit
  end

  # POST /buyers or /buyers.json
  def create
    @buyer = Buyer.new(buyer_params)

    respond_to do |format|
      if @buyer.save
        format.html { redirect_to buyer_url(@buyer), notice: "Buyer was successfully created." }
        format.json { render :show, status: :created, location: @buyer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buyers/1 or /buyers/1.json
  def update
    respond_to do |format|
      if @buyer.update(buyer_params)
        format.html { redirect_to buyer_url(@buyer), notice: "Buyer was successfully updated." }
        format.json { render :show, status: :ok, location: @buyer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buyers/1 or /buyers/1.json
  def destroy
    @buyer.destroy

    respond_to do |format|
      format.html { redirect_to buyers_url, notice: "Buyer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buyer
      @buyer = Buyer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def buyer_params
      params.require(:buyer).permit(:name, :email, :address, :phone_number)
    end
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/views/buyers/_buyer.html.erb
<div id="<%= dom_id buyer %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= buyer.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= buyer.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <%= buyer.address %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Phone number:</strong>
    <%= buyer.phone_number %>
  </p>

</div>

app/views/buyers/_form.html.erb
<%= form_with(model: buyer, class: "contents") do |form| %>
  <% if buyer.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(buyer.errors.count, "error") %> prohibited this buyer from being saved:</h2>

      <ul>
        <% buyer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_field :address, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/buyers/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing buyer</h1>

  <%= render "form", buyer: @buyer %>

  <%= link_to "Show this buyer", @buyer, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to buyers", buyers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/buyers/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Buyers" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Buyers</h1>
    <%= link_to "New buyer", new_buyer_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="buyers" class="min-w-full">
    <% @buyers.each do |buyer| %>
      <%= render buyer %>
      <p>
        <%= link_to "Show this buyer", buyer, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/buyers/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New buyer</h1>

  <%= render "form", buyer: @buyer %>

  <%= link_to "Back to buyers", buyers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/buyers/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @buyer %>

    <%= link_to "Edit this buyer", edit_buyer_path(@buyer), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to buyers", buyers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this buyer", @buyer, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>